dependencies:
  - OpenZeppelin/openzeppelin-contracts@5.5.0

compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@5.5.0'

dotenv: .env

wallets:
  from_key: ${PRIVATE_KEY}

networks:
  sepolia:
    host: https://sepolia.infura.io/v3/${WEB3_INFURA_PROJECT_ID}
    explorer: https://api-sepolia.etherscan.io/api
    required_confirmations: 1
